# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontmodel', '0002_auto_20170722_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(null=True)),
                ('content', models.TextField()),
                ('thumbnail', models.CharField(max_length=200, null=True, verbose_name=b'\xe7\xbc\xa9\xe7\x95\xa5\xe5\x9b\xbe')),
                ('publish_time', models.DateTimeField(null=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('front_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'ordering': ['-publish_time'],
                'db_table': 'y_articles',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articlemodel.ArticleModel')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
                ('relevance_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articlemodel.CommentModel')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_comments',
            },
        ),
        migrations.CreateModel(
            name='ReadArticleCountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.IntegerField(default=0, verbose_name=b'\xe9\x98\x85\xe8\xaf\xbb\xe6\x95\xb0\xe9\x87\x8f')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlemodel.ArticleModel')),
            ],
            options={
                'db_table': 'y_read_article_count',
            },
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'y_sections',
            },
        ),
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('grade', models.IntegerField(null=True)),
                ('relevance_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articlemodel.TagsModel')),
            ],
            options={
                'db_table': 'y_tags',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articlemodel.SectionModel'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(to='articlemodel.TagsModel'),
        ),
    ]
