# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-28 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategoryMenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'wp_article_category_menu',
            },
        ),
        migrations.CreateModel(
            name='ArticleIndexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('index', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisormodel.ArticleCategoryMenuModel')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'wp_article_index',
            },
        ),
    ]
