# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisormodel', '0002_getresourcemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('iphone', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_user_feed_back',
            },
        ),
    ]
