# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontUserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=50, null=True, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0)),
                ('avatar', models.URLField(null=True)),
                ('corporation', models.CharField(max_length=200, null=True, verbose_name='\u6240\u5728\u516c\u53f8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_logout_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1, verbose_name='\u662f\u5426\u9501\u5b9a')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
            ],
            options={
                'db_table': 'y_users',
            },
        ),
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=20, null=True, verbose_name=b'\xe8\x81\x8c\xe7\xa7\xb0\xe5\x90\x8d\xe5\xad\x97')),
                ('job_grade', models.IntegerField(verbose_name=b'\xe8\x81\x8c\xe7\xa7\xb0\xe7\xad\x89\xe7\xba\xa7')),
                ('job_title', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.JobTitleModel')),
            ],
            options={
                'db_table': 'y_job_title',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSectionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20, verbose_name=b'\xe7\xa7\x91\xe5\xae\xa4\xe5\x90\x8d\xe7\xa7\xb0')),
                ('section_grade', models.IntegerField(default=1, verbose_name=b'\xe7\xa7\x91\xe5\xae\xa4\xe7\xad\x89\xe7\xba\xa7')),
                ('professional_section', models.ForeignKey(default=1, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.ProfessionalSectionsModel')),
            ],
            options={
                'db_table': 'y_professional_sections',
            },
        ),
        migrations.AddField(
            model_name='frontusermodel',
            name='jobtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.JobTitleModel'),
        ),
        migrations.AddField(
            model_name='frontusermodel',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.ProfessionalSectionsModel'),
        ),
    ]
