# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontusermodel',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='frontusermodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frontusermodel',
            name='last_logout_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='frontusermodel',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
