# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-31 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0002_auto_20170722_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontusermodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
