# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0005_userbuyordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritesmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
