# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0006_userfavoritesmodel_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritesmodel',
            name='favorite_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionsandanswersmodel.UserCollectCategoryModel'),
        ),
    ]
