# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0008_userpraisemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuyordermodel',
            name='relevance_order',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userbuyordermodel',
            name='status',
            field=models.IntegerField(choices=[(0, b'\xe5\xb7\xb2\xe5\xa4\xb1\xe6\x95\x88'), (1, b'\xe6\x9c\xaa\xe6\x94\xaf\xe4\xbb\x98'), (2, b'\xe5\xb7\xb2\xe6\x94\xaf\xe4\xbb\x98')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='userbuyordermodel',
            name='type',
            field=models.IntegerField(choices=[(1, b'\xe5\xbe\xae\xe4\xbf\xa1'), (2, b'\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x9d')], null=True),
        ),
        migrations.AlterField(
            model_name='userbuyordermodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
