# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-05 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0009_auto_20180601_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuyordermodel',
            name='type',
            field=models.IntegerField(choices=[(1, b'\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x9d'), (2, b'\xe5\xbe\xae\xe4\xbf\xa1')], null=True),
        ),
    ]
