# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-11 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0011_auto_20181124_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontusermodel',
            name='email_validated',
            field=models.BooleanField(default=False),
        ),
    ]
