# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0012_frontusermodel_email_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontusermodel',
            name='full_name',
            field=models.CharField(default=b'', max_length=191),
        ),
    ]
