# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0013_frontusermodel_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontusermodel',
            name='phone_validated',
            field=models.BooleanField(default=False),
        ),
    ]
