# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-06-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0014_frontusermodel_phone_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontusermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='frontusermodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frontusermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
