# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-21 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdcIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=191, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'y_edc_illnesses',
            },
        ),
        migrations.CreateModel(
            name='EdcOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer_name', models.CharField(max_length=191, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'y_edc_organizers',
            },
        ),
        migrations.CreateModel(
            name='EdcPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=191, unique=True)),
                ('url', models.TextField(blank=True)),
                ('icon_url', models.CharField(blank=True, max_length=191)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'y_edc_platforms',
            },
        ),
        migrations.CreateModel(
            name='EdcStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('state', models.TextField()),
                ('type', models.TextField()),
                ('is_top', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('level_type', models.IntegerField(choices=[(3, '\u56fd\u5bb6\u7ea7'), (0, '\u9662\u7ea7'), (1, '\u5e02\u7ea7'), (2, '\u7701\u90e8\u7ea7')], default=0)),
                ('declare_type', models.IntegerField(choices=[(0, '\u81ea\u4e3b\u7533\u62a5'), (1, '\u5b9a\u5411\u59d4\u6258')], default=0)),
                ('is_data_share', models.BooleanField(default=False)),
                ('bg_hash', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('study_website', models.CharField(max_length=191)),
                ('apply_term', models.TextField(blank=True)),
                ('apply_way', models.TextField(blank=True)),
                ('apply_due_date', models.DateField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('edc_platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.EdcPlatform')),
            ],
            options={
                'db_table': 'y_edc_studies',
            },
        ),
        migrations.CreateModel(
            name='EdcStudyIllness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edc_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.EdcStudy')),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.EdcIllness')),
            ],
            options={
                'db_table': 'y_edc_study_illness',
            },
        ),
        migrations.CreateModel(
            name='EdcStudyOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edc_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.EdcStudy')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.EdcOrganizer')),
            ],
            options={
                'db_table': 'y_edc_study_organizer',
            },
        ),
        migrations.CreateModel(
            name='EdcStudyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.TextField()),
                ('department', models.TextField()),
                ('site', models.TextField()),
                ('title', models.TextField()),
                ('type', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('edc_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.EdcStudy')),
            ],
            options={
                'db_table': 'y_edc_study_roles',
            },
        ),
        migrations.CreateModel(
            name='EdcStudySite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('is_top', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('icon_url', models.CharField(blank=True, max_length=191)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('edc_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.EdcStudy')),
            ],
            options={
                'db_table': 'y_edc_study_sites',
            },
        ),
        migrations.AddField(
            model_name='edcstudy',
            name='illnesses',
            field=models.ManyToManyField(through='models.EdcStudyIllness', to='models.EdcIllness'),
        ),
        migrations.AddField(
            model_name='edcstudy',
            name='orgnizers',
            field=models.ManyToManyField(through='models.EdcStudyOrganizer', to='models.EdcOrganizer'),
        ),
    ]
