# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-21 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_import_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstudyrole',
            name='email',
            field=models.TextField(blank=True),
        ),
    ]
