# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-27 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_edcstudyrole_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edcstudy',
            old_name='orgnizers',
            new_name='organizers',
        ),
        migrations.AlterField(
            model_name='edcstudyrole',
            name='type',
            field=models.TextField(choices=[('researcher', '\u7814\u7a76\u8005'), ('expertComm', '\u4e13\u5bb6\u59d4\u5458\u4f1a'), ('pi', 'PI')], default='researcher'),
        ),
    ]
