# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20180927_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='edcstudysite',
            name='org_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='edcstudysite',
            name='org_name',
            field=models.CharField(blank=True, max_length=191),
        ),
    ]
