# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20180927_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edcstudy',
            name='bg_hash',
        ),
        migrations.AddField(
            model_name='edcstudy',
            name='bg_oss_key',
            field=models.TextField(blank=True),
        ),
    ]
