# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-08 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0007_auto_20180928_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191, unique=True)),
                ('content_from', models.IntegerField(choices=[(1, '\u9996\u9875Banner'), (3, '\u9996\u9875\u7cbe\u54c1\u6559\u7a0b'), (2, '\u9996\u9875\u6700\u65b0\u8fdb\u5c55')], default=1)),
                ('introduction', models.TextField(blank=True)),
                ('url', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('image_url_key', models.CharField(blank=True, max_length=191)),
                ('content_time', models.DateTimeField(auto_now_add=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'y_content_recommend',
            },
        ),
    ]
