# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-10-29 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0010_auto_20180605_1745'),
        ('models', '0009_contentrecommend_default_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
                ('description', models.TextField(blank=True)),
                ('studies', models.ManyToManyField(related_name='networks', to='models.EdcStudy')),
            ],
            options={
                'db_table': 'y_network',
            },
        ),
        migrations.CreateModel(
            name='NetworkApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=191)),
                ('site', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Network')),
                ('studies', models.ManyToManyField(related_name='network_applications', to='models.EdcStudy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'db_table': 'y_network_application',
            },
        ),
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=191)),
                ('department', models.CharField(max_length=191)),
                ('duty', models.CharField(max_length=191)),
                ('edc_user_id', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='models.NetworkApplication')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Network')),
            ],
            options={
                'db_table': 'y_network_member',
            },
        ),
    ]
