# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-13 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_update_edc_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkapplication',
            name='status',
            field=models.IntegerField(choices=[(0, '\u672a\u5ba1\u6838'), (1, '\u5df2\u5ba1\u6838')], default=0),
        ),
        migrations.AddField(
            model_name='networkmember',
            name='medieco_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
