# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0010_auto_20180605_1745'),
        ('models', '0013_auto_20181114_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel'),
        ),
        migrations.AlterUniqueTogether(
            name='networkapplication',
            unique_together=set([('network', 'user')]),
        ),
    ]
