# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-21 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_auto_20181119_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMemberB4Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_raw', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'y_network_member_before_account',
            },
        ),
        migrations.AddField(
            model_name='networkmember',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networkapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_applications', to='frontmodel.FrontUserModel'),
        ),
        migrations.AddField(
            model_name='networkmemberb4account',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NetworkMember'),
        ),
    ]
