# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def generate_random_code():
    return uuid.uuid4().get_hex()

class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20181121_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmemberb4account',
            name='code',
            # NOTE，在migration时，添加一个不允许为 null 的字段时，必须提供一个默认值，
            # 又因为这个字段是 unique 的，所以使用随机值来填充，
            # 生产环境中，这个表不存在，所以这个默认值没有副作用。
            field=models.CharField(max_length=32, default=generate_random_code, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='networkmemberb4account',
            name='used_at',
            field=models.DateTimeField(null=True),
        ),
    ]
