# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20181129_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkcourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='networkcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='networkcourse',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='models.Network'),
        ),
    ]
