# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-01 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0001_initial'),
        ('models', '0019_network_course_default_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkcourse',
            name='medal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anniversary.medalModel'),
        ),
    ]
