# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-05 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0011_auto_20181124_1224'),
        ('models', '0020_networkcourse_medal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkcoursetrainlog',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NetworkCourseVideo'),
        ),
        migrations.RemoveField(
            model_name='networkcoursetrainlog',
            name='course',
        ),
        migrations.AlterUniqueTogether(
            name='networkcoursetrainlog',
            unique_together=set([('participant', 'video')]),
        ),
        migrations.AlterUniqueTogether(
            name='networkcoursetrainprogress',
            unique_together=set([('participant', 'course')]),
        ),
    ]
