# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-08 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0011_auto_20181124_1224'),
        ('models', '0021_auto_20181205_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMemberDepartmentProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=191, unique=True)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.ProfessionalSectionsModel')),
            ],
            options={
                'db_table': 'y_network_memeber_department_profession',
            },
        ),
        migrations.CreateModel(
            name='NetworkMemberTitleJobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191, unique=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.JobTitleModel')),
            ],
            options={
                'db_table': 'y_network_member_title_jobtitle',
            },
        ),
        migrations.AlterUniqueTogether(
            name='networkmembertitlejobtitle',
            unique_together=set([('title', 'job_title')]),
        ),
        migrations.AlterUniqueTogether(
            name='networkmemberdepartmentprofession',
            unique_together=set([('department', 'profession')]),
        ),
    ]
