# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-19 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0013_frontusermodel_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0023_import_department_job_mapper'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, '\u5df2\u53d1\u5e03'), (0, '\u8349\u7a3f')], default=0)),
                ('scope', models.IntegerField(choices=[(0, '\u516c\u5f00'), (1, '\u79d1\u7814\u7f51\u7edc')], default=0)),
                ('top', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_notices', to='models.Network')),
                ('publish_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'y_network_notices',
            },
        ),
        migrations.CreateModel(
            name='NetworkNoticeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NetworkNotice')),
            ],
            options={
                'db_table': 'y_network_notice_attachment',
            },
        ),
        migrations.CreateModel(
            name='NetworkNoticeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('read', '\u9605\u8bfb'), ('share', '\u5206\u4eab')], default='read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NetworkNotice')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'db_table': 'y_network_notice_stat',
            },
        ),
        migrations.CreateModel(
            name='NetworkTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'y_network_tags',
            },
        ),
        migrations.AlterField(
            model_name='contentrecommend',
            name='content_from',
            field=models.IntegerField(choices=[(1, '\u9996\u9875Banner'), (2, '\u9996\u9875\u6700\u65b0\u8fdb\u5c55'), (3, '\u9996\u9875\u7cbe\u54c1\u6559\u7a0b')], default=1),
        ),
        migrations.AlterField(
            model_name='edcstudy',
            name='level_type',
            field=models.IntegerField(choices=[(3, '\u56fd\u5bb6\u7ea7'), (2, '\u7701\u90e8\u7ea7'), (1, '\u5e02\u7ea7'), (0, '\u9662\u7ea7')], default=0),
        ),
        migrations.AlterField(
            model_name='edcstudyrole',
            name='type',
            field=models.TextField(choices=[('expertComm', '\u4e13\u5bb6\u59d4\u5458\u4f1a'), ('pi', 'PI'), ('researcher', '\u7814\u7a76\u8005')], default='researcher'),
        ),
        migrations.AddField(
            model_name='networknotice',
            name='tags',
            field=models.ManyToManyField(db_table='y_network_notice_tag', related_name='notices', to='models.NetworkTag'),
        ),
        migrations.AlterUniqueTogether(
            name='networknoticeattachment',
            unique_together=set([('notice', 'file_key')]),
        ),
    ]
