# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_auto_20190621_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='copdlivetalker',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expert',
            name='introduction',
            field=models.TextField(blank=True, verbose_name=b'\xe7\xae\x80\xe4\xbb\x8b'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='models.Image', verbose_name=b'\xe5\xa4\xb4\xe5\x83\x8f'),
        ),
    ]
