# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-14 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontmodel', '0010_auto_20180605_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='anniversaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary_times', models.IntegerField(default=2)),
                ('data', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'db_table': 'y_anniversary',
            },
        ),
        migrations.CreateModel(
            name='medalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='\u52cb\u7ae0\u540d')),
                ('uid', models.CharField(max_length=20, unique=True, verbose_name='\u52cb\u7ae0uid')),
                ('is_valid', models.BooleanField(default=True, verbose_name='\u662f\u5426\u542f\u7528')),
                ('medal_type', models.CharField(choices=[(0, '\u666e\u901a\u52cb\u7ae0')], default=0, max_length=10, verbose_name='\u52cb\u7ae0\u7c7b\u578b')),
                ('pic_url', models.URLField(verbose_name='\u52cb\u7ae0\u56fe\u8def\u5f84')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='\u52cb\u7ae0\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'y_medal',
            },
        ),
        migrations.CreateModel(
            name='specialTopicCommentLikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'y_special_topic_comment_like',
            },
        ),
        migrations.CreateModel(
            name='specialTopicCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_type', models.CharField(default='twoYear', max_length=20, verbose_name='\u6d3b\u52a8\u7c7b\u578b')),
                ('comments', models.CharField(max_length=2000, verbose_name='\u6d3b\u52a8\u7559\u8a00')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_publish', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5c55\u793a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'db_table': 'y_special_topic_comment',
            },
        ),
        migrations.CreateModel(
            name='specialTopicCommentReplyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=2000, verbose_name='\u7559\u8a00\u56de\u590d')),
                ('reply_user', models.CharField(default='\u5c0f\u5496', max_length=20, verbose_name='\u56de\u590d\u4eba\u6635\u79f0')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anniversary.specialTopicCommentModel')),
            ],
            options={
                'db_table': 'y_special_topic_comment_replay',
            },
        ),
        migrations.CreateModel(
            name='userMedalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_disabled', models.BooleanField(default=False, verbose_name='\u662f\u5426\u88ab\u5265\u593a\u52cb\u7ae0')),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anniversary.medalModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'db_table': 'y_user_medal',
            },
        ),
        migrations.AddField(
            model_name='specialtopiccommentlikemodel',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anniversary.specialTopicCommentModel'),
        ),
        migrations.AddField(
            model_name='specialtopiccommentlikemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel'),
        ),
        migrations.AlterUniqueTogether(
            name='usermedalmodel',
            unique_together=set([('medal', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='specialtopiccommentlikemodel',
            unique_together=set([('user', 'comment')]),
        ),
    ]
