# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anniversary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medalmodel',
            name='pic_negative_ss_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medalmodel',
            name='pic_ss_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medalmodel',
            name='medal_type',
            field=models.CharField(choices=[(0, '\u666e\u901a\u52cb\u7ae0'), (1, '\u5468\u5e74\u52cb\u7ae0')], default=0, max_length=10, verbose_name='\u52cb\u7ae0\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='medalmodel',
            name='name',
            field=models.CharField(max_length=191, unique=True, verbose_name='\u52cb\u7ae0\u540d'),
        ),
    ]
