# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-03 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontmodel', '0003_auto_20171031_0158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('is_active', models.SmallIntegerField(default=0)),
                ('rank', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'y_banner',
            },
        ),
        migrations.CreateModel(
            name='MethodArticleContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_login', models.SmallIntegerField(default=0)),
                ('rank', models.SmallIntegerField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'y_method_article_content',
            },
        ),
        migrations.CreateModel(
            name='MethodArticleContentSectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'y_method_article_content_section',
            },
        ),
        migrations.CreateModel(
            name='MethodArticleInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(null=True)),
                ('thumbnail', models.CharField(max_length=200, null=True)),
                ('rank', models.SmallIntegerField(null=True)),
                ('status', models.SmallIntegerField(default=3)),
                ('file_name', models.CharField(max_length=1000, null=True)),
                ('arrange', models.SmallIntegerField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_method_article_info',
            },
        ),
        migrations.CreateModel(
            name='MethodArticleRelatedReadingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange', models.SmallIntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('related_reading_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_reding_article', to='methodmodel.MethodArticleInfoModel')),
                ('relevance_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relevance_article', to='methodmodel.MethodArticleInfoModel')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_method_article_related_reading',
            },
        ),
        migrations.CreateModel(
            name='MethodCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('grade', models.IntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.SmallIntegerField(default=1, null=True)),
                ('rank', models.SmallIntegerField(default=1)),
                ('column', models.SmallIntegerField(null=True)),
                ('relevance_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodCategoryModel')),
            ],
            options={
                'db_table': 'y_method_category',
            },
        ),
        migrations.AddField(
            model_name='methodarticleinfomodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodCategoryModel'),
        ),
        migrations.AddField(
            model_name='methodarticleinfomodel',
            name='front_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel'),
        ),
        migrations.AddField(
            model_name='methodarticlecontentmodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodArticleInfoModel'),
        ),
        migrations.AddField(
            model_name='methodarticlecontentmodel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodArticleContentSectionModel'),
        ),
    ]
