# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodarticleinfomodel',
            name='read_counts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
