# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodmodel', '0002_methodarticleinfomodel_read_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodArticleTopicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('status', models.SmallIntegerField(default=1)),
                ('arrange', models.SmallIntegerField(null=True)),
                ('create_time', models.DateTimeField(null=True)),
                ('read_counts', models.IntegerField(default=0)),
                ('thumbnail', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_method_article_topic',
            },
        ),
        migrations.CreateModel(
            name='TopicRelatedMethodArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrange', models.SmallIntegerField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_topic_related_method_article',
            },
        ),
        migrations.AddField(
            model_name='bannermodel',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='methodarticleinfomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodCategoryModel'),
        ),
        migrations.AddField(
            model_name='topicrelatedmethodarticlemodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodArticleInfoModel'),
        ),
        migrations.AddField(
            model_name='topicrelatedmethodarticlemodel',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodArticleTopicModel'),
        ),
    ]
