# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodmodel', '0003_auto_20180129_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWordGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_key_word_group',
            },
        ),
        migrations.CreateModel(
            name='KeyWordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.KeyWordGroupModel')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_key_word',
            },
        ),
        migrations.CreateModel(
            name='KeyWordRelevanceArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.SmallIntegerField(null=True)),
                ('type', models.SmallIntegerField(choices=[(1, '\u7814\u7a76\u65b9\u6cd5'), (2, '\u4e13\u9898\u5408\u96c6')], null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodmodel.KeyWordGroupModel')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_key_word_relevance_article',
            },
        ),
    ]
