# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-25 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontmodel', '0004_userfavoritesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('status', models.IntegerField(choices=[(0, b'\xe5\xb7\xb2\xe5\x88\xa0\xe9\x99\xa4'), (1, b'\xe6\x9c\xaa\xe5\x88\xa0\xe9\x99\xa4')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontmodel.FrontUserModel')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_video_comment',
            },
        ),
        migrations.CreateModel(
            name='VideoCourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('teach_intro', models.TextField(max_length=2000, null=True)),
                ('thumbnail', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('related_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videomodel.VideoCourseModel')),
            ],
            options={
                'db_table': 'y_video_course',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000, null=True)),
                ('polyv_vid', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, b'\xe8\x8d\x89\xe7\xa8\xbf'), (1, b'\xe5\xb7\xb2\xe5\x8f\x91\xe5\xb8\x83')], default=0)),
                ('is_pay', models.IntegerField(choices=[(0, b'\xe5\x85\x8d\xe8\xb4\xb9\xe8\xaf\xbe\xe7\xa8\x8b'), (1, b'\xe4\xbb\x98\xe8\xb4\xb9\xe8\xaf\xbe\xe7\xa8\x8b'), (2, b'\xe6\x9b\xb4\xe6\x96\xb0\xe4\xb8\xad')], default=0)),
                ('video_time', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videomodel.VideoCourseModel')),
            ],
            options={
                'db_table': 'y_video',
            },
        ),
        migrations.CreateModel(
            name='VideoRelatedDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomodel.VideoModel')),
            ],
            options={
                'db_table': 'y_video_realted_data',
            },
        ),
        migrations.AddField(
            model_name='videocommentmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videomodel.VideoModel'),
        ),
    ]
