# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodmodel', '0006_methodcategorymodel_type'),
        ('videomodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachIntroModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_intro', models.TextField(max_length=2000, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'y_teach_intro',
            },
        ),
        migrations.RemoveField(
            model_name='videocoursemodel',
            name='related_course',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='course',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodCategoryModel'),
        ),
        migrations.DeleteModel(
            name='VideoCourseModel',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='teach_intro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videomodel.TeachIntroModel'),
        ),
    ]
