# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodmodel', '0006_methodcategorymodel_type'),
        ('videomodel', '0002_auto_20180426_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videomodel',
            old_name='category',
            new_name='course',
        ),
        migrations.AddField(
            model_name='teachintromodel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodCategoryModel'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='course_main',
            field=models.TextField(null=True),
        ),
    ]
