# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0003_auto_20180426_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='teach_intro',
        ),
    ]
