# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodmodel', '0006_methodcategorymodel_type'),
        ('videomodel', '0004_remove_videomodel_teach_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=2000, null=True)),
                ('thumbnail', models.CharField(max_length=200, null=True)),
                ('teach_intro', models.TextField(max_length=2000, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodCategoryModel')),
            ],
            options={
                'db_table': 'y_course',
            },
        ),
        migrations.RemoveField(
            model_name='teachintromodel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='videomodel',
            name='summary',
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeachIntroModel',
        ),
    ]
