# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0005_auto_20180426_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='summary',
            new_name='course_intro',
        ),
    ]
