# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-26 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0007_videomodel_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
