# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0008_coursemodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
    ]
