# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-28 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0009_auto_20180427_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocommentmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='videocommentmodel',
            name='relevance_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videomodel.VideoCommentModel'),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='status',
            field=models.IntegerField(choices=[(0, b'\xe5\xb7\xb2\xe5\x88\xa0\xe9\x99\xa4'), (1, b'\xe5\xb7\xb2\xe5\x8f\x91\xe5\xb8\x83'), (2, b'\xe8\x8d\x89\xe7\xa8\xbf')], default=2),
        ),
    ]
