# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0010_auto_20180428_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='thumbnail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
