# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0011_videomodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='polyv_vid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
