# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomodel', '0014_auto_20180728_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='teacher_introduction',
            field=models.TextField(blank=True),
        ),
    ]
