# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-10 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsandanswersmodel', '0003_auto_20171031_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectquestionmodel',
            name='collect_question',
        ),
        migrations.RemoveField(
            model_name='collectquestionmodel',
            name='username',
        ),
        migrations.DeleteModel(
            name='CollectQuestionModel',
        ),
    ]
