# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodel', '0003_auto_20171031_0158'),
        ('methodmodel', '0001_initial'),
        ('questionsandanswersmodel', '0004_auto_20171110_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMessagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.SmallIntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'y_my_messages',
            },
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='relevance_method_article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodmodel.MethodArticleInfoModel'),
        ),
        migrations.AddField(
            model_name='mymessagesmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsandanswersmodel.QuestionsModel'),
        ),
        migrations.AddField(
            model_name='mymessagesmodel',
            name='replay_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsandanswersmodel.AnswersModel'),
        ),
        migrations.AddField(
            model_name='mymessagesmodel',
            name='replay_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_name', to='frontmodel.FrontUserModel'),
        ),
    ]
