# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-01-17 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionsandanswersmodel', '0005_auto_20180103_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='read_counts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
